# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: library/mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=atrasti
      - MYSQL_USER=eduard
      - MYSQL_PASSWORD=edvin123!
      - MYSQL_ROOT_PASSWORD=edvin123!
    ports:
      - 3306:3306